### PR TITLE
Fix/error message readability 291

### LINKED ISSUE #291: Error message is hard to read in validation panel
# Problem

When I enter invalid JSON, the validation message is shown, but it is not easy to notice or read quickly. The error area should be clearer and easier to scan.

## Before

Image

> The error message is difficult to read and the validation area is not draggable.

## After

Image
Image

> The error message is now easily readable and the validation window is draggable (like VS Code terminal).

### Changes Made:

1. **Better Error Messages** (`src/utils/parseSchema.ts`)
   - Enhanced JSON/YAML error parsing to include line number, column, and character position
   - Format: `Invalid JSON: [error message] (line X column Y) (near character N)`

2. **Resizable Validation Panel** (`src/components/MonacoEditor.tsx`)
   - Converted validation area from fixed-height to draggable vertical split
   - Added `PanelResizeHandle` to allow users to expand/collapse the error panel
   - Validation panel always visible and readable

3. **Improved UI Styling** (`src/App.css`)
   - Added visual drag handle indicator
   - Smooth cursor feedback (`cursor-row-resize`)
   - Better visual hierarchy for the validation section

### Result:
- ✅ Error messages now clearly show exact location of JSON syntax errors
- ✅ Validation panel is resizable like VS Code terminal
- ✅ Users can easily expand the panel to read full error messages

### PR DESCRIPTION
**Pull request by Muawiya-contact**
## Summary
This PR makes error messages in the schema editor much easier to read and work with. When validation errors happen, users will now see them clearly without text overflowing, and the panel behaves more like VS Code's integrated terminal.

## What Changed
I improved the **validation panel** (the error message box at the bottom of the editor) with:

### Visual Improvements
- **Better colors**: Error text is now brighter/darker depending on light/dark theme so it's actually readable (not washed out)
- **Better spacing**: Error messages have more room to breathe with improved padding and line-height

### Technical Improvements  
- **Text wrapping**: Long error messages now wrap naturally instead of running off-screen
- **Smooth scrolling**: Messages that are too long to fit can be scrolled, with a nice VS Code-style scrollbar
- **Smart sizing**: The panel is big enough to see errors (minimum 60px) but doesn't take over the screen (maximum 200px)

## Why This Matters
When users paste invalid JSON or schemas with validation issues, they should be able to **instantly understand what went wrong**. Instead of squinting at dim red text or scrolling horizontally, errors are now clear and accessible.

## Img
Screenshot 2026-04-17 211737

## Testing
✅ Tested on both light and dark themes  
✅ Tried with short error messages (looks good)  
✅ Tried with very long error messages (scrolls perfectly)  
✅ Scrollbar works smoothly with mouse wheel  
✅ No breaking changes - everything still works

## Issue
Closes #291

### CODE REVIEW

File: src/components/MonacoEditor.tsx [hunk 1]
```diff
@@ -58,15 +58,15 @@ const SUPPORTED_DIALECTS = ["https://json-schema.org/draft/2020-12/schema"];
 const getValidationUI = (theme: "light" | "dark") => ({
   success: {
     message: "✓ Valid JSON Schema",
-    className: "text-green-400 font-semibold",
+    className: "text-green-400 font-semibold break-words",
```
Comment (AgniveshChaubey) [inline src/components/MonacoEditor.tsx]: why do you think we need word-break here?

File: src/components/MonacoEditor.tsx [hunk 2]
```diff
@@ -58,15 +58,15 @@ const SUPPORTED_DIALECTS = ["https://json-schema.org/draft/2020-12/schema"];
...
   },
   warning: {
     message: `⚠ Schema dialect not provided. Using default dialect: ${DEFAULT_SCHEMA_DIALECT}`,
-    className: theme === "dark" ? "text-yellow-400" : "text-amber-800",
+    className: theme === "dark" ? "text-yellow-400 break-words" : "text-amber-800 break-words",
   },
   error: {
     message: "✗ ",
-    className: "text-red-400",
+    className: theme === "dark" ? "text-red-300 font-semibold break-words" : "text-red-600 font-semibold break-words",
```
Comment (AgniveshChaubey) [inline src/components/MonacoEditor.tsx]: I think we can leave the font color as is in dark mode and just make the red color a bit darker in light mode. Also, I think we can avoid keeping the font in bold.

File: src/components/MonacoEditor.tsx [hunk 3]
```diff
@@ -281,7 +281,7 @@ const MonacoEditor = () => {
     }, 300);
 
     return () => clearTimeout(timeout);
-  }, [schemaText, schemaFormat]);
+  }, [schemaText, schemaFormat, VALIDATION_UI]);
```
Comment (AgniveshChaubey) [inline src/components/MonacoEditor.tsx]: are you sure `VALIDATION_UI` is required in dependency array?

**Comment by AgniveshChaubey** [comment]
image


Lets keep the default editor panel height as it was earlier. Just making the validation message section resizable should be enough.

File: src/components/MonacoEditor.tsx (hunk 1 above)
Comment (Muawiya-contact) [reply src/components/MonacoEditor.tsx]: I added `break-words` to handle long validation messages that were overflowing, but I can remove it if you prefer and keep wrapping simpler.

File: src/components/MonacoEditor.tsx (hunk 2 above)
Comment (Muawiya-contact) [reply src/components/MonacoEditor.tsx]: Okay, I’ll keep the default dark mode color and just adjust the light mode red. I’ll also remove the bold styling.

File: src/components/MonacoEditor.tsx (hunk 3 above)
Comment (Muawiya-contact) [reply src/components/MonacoEditor.tsx]: let me check it.

**Comment by Muawiya-contact** [comment]
I just made the validation panel fully resizable! 

**How to Use:**
Just grab the divider line between the code editor and the "✓ Valid JSON Schema" message box and drag up/down to resize!

**Why This Matters:**
Users who work with long error messages can now expand the validation panel. Users who want more editor space can shrink it. Full control! 

---

This follows the same resizable pattern as VS Code's terminal - users can adjust exactly how they want it.

File: src/components/MonacoEditor.tsx (hunk 3 above)
Comment (Muawiya-contact) [reply src/components/MonacoEditor.tsx]: Yes, you are right i have remove it now.

**Comment by AgniveshChaubey** [comment]
Before:
image


After:
image


I meant to say let's not keep the Validation Message section this big by default. The default height should be the same as the “before” one -- just that it is now resizable.

**Comment by Muawiya-contact** [comment]
> Before: image
> 
> After: image
> 
> I meant to say let's not keep the Validation Message section this big by default. The default height should be the same as the “before” one -- just that it is now resizable.

@AgniveshChaubey Now it's the same as the default size in the main repo
## Now
Screenshot 2026-04-18 113438

**Review by AgniveshChaubey — APPROVED** [review]
Required some minor changes, other than than, looks good
