### PR TITLE
fix: improve validation message contrast in light theme

### LINKED ISSUE #78: Bug : Schema Warning Text Unreadable in Light Theme
**Description**
The warning message *"Schema dialect not provided. Using default dialect..."* is displayed in a fixed yellow color. While this is readable in Dark Mode, it has extremely low contrast against the white background in **Light Mode**, making it nearly impossible to read.

**Expected Behavior**
The warning text should be legible in both themes. It should use theme-aware colors (e.g., dark amber/brown for light mode and bright yellow for dark mode) to ensure accessible contrast ratios.

**Steps to Reproduce**
1. Switch the application to **Light Theme**.
2. Load a schema that triggers the default dialect warning (i.e., omit `$schema`).
3. Observe the warning text color in the editor/log area.
## Screenshots

Dark theme (readable):

Image

Light theme (low contrast):

Image

I would love to fix this issue @AgniveshChaubey  @jagpreetrahi !

### PR DESCRIPTION
**Pull request by itvi-1234**
## Summary

This PR fixes the low contrast issue with validation messages in **Light Theme**. Previously, the warning message "Schema dialect not provided..." used a bright yellow color (`text-yellow-400`) that was unreadable against the white background in light mode.

**Changes:**
- Implemented theme-aware conditional rendering in [MonacoEditor.tsx](cci:7://file:///home/sumit/studio-json-schema/src/components/MonacoEditor.tsx:0:0-0:0) that applies different colors based on the current theme
- Light theme now uses `text-amber-800` (dark brownish-orange) for warnings
- Dark theme continues to use `text-yellow-400` (bright yellow) for warnings
- Also improved success and error message colors for consistency across both themes

## Type of Change

- [x] Bug fix
- [ ] New feature
- [ ] Breaking change
- [ ] Documentation update

## Issue Number

Closes #78 

**Before (Light Theme):**

Screenshot from 2026-02-13 16-18-20

*(Bright yellow text, nearly invisible on white background)*

**After (Light Theme):**

image

*(Dark amber text, clearly readable on white background)*

## Does this PR introduce a breaking change?

No. This only changes the visual styling of validation messages to improve readability. No API or functionality changes.

## If relevant, did you update the documentation?

No documentation update required for this UI enhancement.

### CODE REVIEW

File: src/components/MonacoEditor.tsx [hunk 1]
```diff
@@ -155,13 +155,13 @@ const MonacoEditor = () => {
         setSchemaValidation(
           !dialect && typeof parsedSchema !== "boolean"
             ? {
-                status: "warning",
-                message: VALIDATION_UI["warning"].message,
-              }
+              status: "warning",
```
Comment (AgniveshChaubey) [inline src/components/MonacoEditor.tsx]: why this indentation changes?

**Comment by AgniveshChaubey** [comment]
please bump the patch version
